version: '3'

services:
  api:
    container_name: api
    image: node:erbium # node.js 12のLTSコードネーム
    volumes:
      - ./src:/src
    command: bash /src/launch.sh
    restart: always
    ports:
      - 30000:3000

  db:
    container_name: db
    image: mysql:5.7
    ports: 
      - 3306:3306
    restart: always
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: crud
